/**
 * Local music library browser.
 *
 * In dev mode, fetches a pre-generated index of the local music collection
 * (generated by scripts/index-music.sh). The music directory is served
 * by Vite's dev server via the fs.allow configuration.
 *
 * In production builds, the library is unavailable (returns empty).
 */

export interface LibraryEntry {
  artist: string;
  album: string;
  title: string;
  path: string;
}

let cachedLibrary: LibraryEntry[] | null = null;

/**
 * Fetch the local music library index.
 * Returns an empty array if the index is not available (production, or not generated).
 */
export async function fetchMusicLibrary(): Promise<LibraryEntry[]> {
  if (cachedLibrary) return cachedLibrary;

  try {
    const response = await fetch('/music-index.json');
    if (!response.ok) return [];
    cachedLibrary = await response.json();
    return cachedLibrary ?? [];
  } catch {
    return [];
  }
}

/**
 * Get unique artists from the library.
 */
export function getArtists(library: LibraryEntry[]): string[] {
  return [...new Set(library.map(e => e.artist))].sort();
}

/**
 * Get albums for a given artist.
 */
export function getAlbums(library: LibraryEntry[], artist: string): string[] {
  return [...new Set(library.filter(e => e.artist === artist).map(e => e.album))].sort();
}

/**
 * Get tracks for a given artist and album.
 */
export function getTracks(library: LibraryEntry[], artist: string, album?: string): LibraryEntry[] {
  return library.filter(e => e.artist === artist && (!album || e.album === album));
}
